# .scrutinizer.yml
filter:
    excluded_paths:
        - vendor/*
        - node_modules/*
        - database/*
        - tests/*
        - app/Console/*
build:
    environment:
        php:
            version: 5.6
    dependencies:
        override:
            - composer install --prefer-source

    # Run after dependencies
    project_setup:
        before:
            - mysql -e "CREATE DATABASE dbs"
            - cp .env.scrutinizer .env
        
        override:
            - php artisan migrate --force
            - php artisan db:seed --force
    
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=coverage.xml'
                coverage:
                    file: 'coverage.xml'
                    format: 'php-clover'
    deployment:
        -
            branch: master
            commands:
                - wget https://forge.laravel.com/servers/84940/sites/192097/deploy/http?token=LvlFzgnYu5y8hcISeP2Jfc6v4Td5lwtC1uFvqwvf
        -
            branch: development
            commands:
                - wget https://forge.laravel.com/servers/25695/sites/82269/deploy/http?token=DV3J7PW1HpqOfrA2PokuB60pf9Ei3cXI93ZpSvaJ
